name: Update profile submodule

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update submodule to latest
        run: |
          git submodule init
          git submodule update
          git submodule update --remote --merge
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
            add: 'JanMalch'
            message: 'feat: update profile in submodule'
            push: true
